name: ci

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/latest/download/install
          extra_nix_config: experimental-features = flakes nix-command

      - name: Set up cachix
        uses: cachix/cachix-action@v8
        with:
          name: figsoda
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build with nix
        run: nix build .#ymdl
