name: update

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
          extra_nix_config: experimental-features = flakes nix-command

      - name: Update lock file
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          nix flake update --commit-lock-file
          git push

      - name: Set up cachix
        uses: cachix/cachix-action@v10
        with:
          name: figsoda
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build with nix
        run: nix build .#{rust-templates,ymdl}
